name: Entrega Blindada

on:
  push:
    branches: ["main"]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar HTMLHint
        run: npm install -g htmlhint

      - name: Rodar Linter HTML
        run: htmlhint "**/*.html"


  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Criar pasta dist
        run: |
          mkdir dist
          cp *.html dist/ || true
          cp *.css dist/ || true

      - name: Upload artefato
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: site
          path: dist

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist